name: QA

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci --prefer-offline --force
      - run: npm run lint
      - run: npm run typecheck

  chromatic:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm ci --prefer-offline --force
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: build:storybook
          exitZeroOnChanges: true
          exitOnceUploaded: true
          autoAcceptChanges: main

  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Use Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 16
  #         cache: npm
  #     - run: npm ci --prefer-offline
  #     - run: npm run test:coverage
  #     - name: Codecov
  #       uses: codecov/codecov-action@v1.0.6
